"""Audit JSONL data for provenance gaps, secrets, and hidden-reasoning leakage."""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass, field
from pathlib import Path

from .data import DISALLOWED_FIELDS, DataValidationError, load_jsonl


SECRET_PATTERNS = (
    re.compile(r"gh[pousr]_[A-Za-z0-9_]{20,}"),
    re.compile(r"sk-[A-Za-z0-9_-]{20,}"),
    re.compile(r"AKIA[0-9A-Z]{16}"),
    re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
)
INJECTION_PATTERN = re.compile(
    r"(?i)(ignore\s+(?:all\s+)?previous|reveal\s+(?:the\s+)?system prompt|developer message)"
)


@dataclass
class AuditReport:
    dataset: str
    records: int = 0
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.errors

    def to_dict(self) -> dict:
        return {
            "dataset": self.dataset,
            "records": self.records,
            "errors": self.errors,
            "warnings": self.warnings,
            "status": "pass" if self.ok else "fail",
        }


def _scan_text(report: AuditReport, record_id: str, text: str, field: str) -> None:
    for pattern in SECRET_PATTERNS:
        if pattern.search(text):
            report.errors.append(f"{record_id}:{field}: possible secret pattern {pattern.pattern}")
    if INJECTION_PATTERN.search(text):
        report.warnings.append(f"{record_id}:{field}: prompt-injection-like text detected")


def audit_dataset(path: str | Path) -> AuditReport:
    report = AuditReport(dataset=str(path))
    path = Path(path)
    if not path.exists():
        report.errors.append(f"missing dataset: {path}")
        return report
    try:
        examples = load_jsonl(path)
    except (DataValidationError, FileNotFoundError) as exc:
        report.errors.append(str(exc))
        return report
    report.records = len(examples)
    with path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            if not line.strip():
                continue
            raw = json.loads(line)
            hidden = sorted(DISALLOWED_FIELDS.intersection(raw))
            if hidden:
                report.errors.append(
                    f"{path}:{line_number}: hidden-reasoning fields present: {', '.join(hidden)}"
                )
            record_id = str(raw.get("id", f"line-{line_number}"))
            _scan_text(report, record_id, str(raw.get("prompt", "")), "prompt")
            _scan_text(report, record_id, str(raw.get("answer", "")), "answer")
            if str(raw.get("source", "")).lower() in {"unknown", ""}:
                report.errors.append(f"{record_id}: source is missing or unknown")
            if str(raw.get("license", "")).lower() in {"unknown", ""}:
                report.errors.append(f"{record_id}: license is missing or unknown")
    return report


def audit_split_overlap(train_path: str | Path, eval_path: str | Path) -> list[str]:
    try:
        train_ids = {item.id for item in load_jsonl(train_path)}
        eval_ids = {item.id for item in load_jsonl(eval_path)}
    except (DataValidationError, FileNotFoundError) as exc:
        return [str(exc)]
    overlap = sorted(train_ids.intersection(eval_ids))
    if overlap:
        return [f"train/eval id overlap: {', '.join(overlap)}"]
    return []


def render_report(reports: list[AuditReport], overlap_errors: list[str]) -> str:
    lines = ["# Data audit", "", "Generated by `python -m cognition_slm.audit`.", ""]
    overall_errors = [error for report in reports for error in report.errors] + overlap_errors
    lines.append(f"Status: **{'PASS' if not overall_errors else 'FAIL'}**")
    lines.append("")
    for report in reports:
        lines.append(f"## `{report.dataset}`")
        lines.append("")
        lines.append(f"- Records: {report.records}")
        lines.append(f"- Errors: {len(report.errors)}")
        lines.append(f"- Warnings: {len(report.warnings)}")
        for message in report.errors:
            lines.append(f"- ERROR: {message}")
        for message in report.warnings:
            lines.append(f"- WARNING: {message}")
        lines.append("")
    if overlap_errors:
        lines.append("## Split checks")
        lines.append("")
        for message in overlap_errors:
            lines.append(f"- ERROR: {message}")
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--train", required=True)
    parser.add_argument("--eval", dest="eval_path")
    parser.add_argument("--report")
    args = parser.parse_args()
    reports = [audit_dataset(args.train)]
    overlap_errors: list[str] = []
    if args.eval_path:
        reports.append(audit_dataset(args.eval_path))
        overlap_errors = audit_split_overlap(args.train, args.eval_path)
    rendered = render_report(reports, overlap_errors)
    if args.report:
        report_path = Path(args.report)
        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text(rendered, encoding="utf-8")
    print(json.dumps({"reports": [report.to_dict() for report in reports], "overlap_errors": overlap_errors}, indent=2))
    if any(report.errors for report in reports) or overlap_errors:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
