"""Project-authored synthetic examples used for the smoke project."""

from __future__ import annotations

import json
from pathlib import Path


TRAIN_ROWS = [
    {
        "id": "train-factorial-loop",
        "prompt": "Write a Python function that returns the factorial of a non-negative integer n.",
        "answer": "def factorial(n):\n    result = 1\n    for value in range(2, n + 1):\n        result *= value\n    return result",
        "task_type": "code_generation",
        "confidence": 0.92,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-palindrome",
        "prompt": "Write a Python function that returns True when text reads the same backward after lowercasing.",
        "answer": "def is_palindrome(text):\n    normalized = text.lower()\n    return normalized == normalized[::-1]",
        "task_type": "code_generation",
        "confidence": 0.9,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-debug-off-by-one",
        "prompt": "Fix this function so it returns the sum of every item: def total(items): return sum(items[:-1])",
        "answer": "def total(items):\n    return sum(items)",
        "task_type": "code_debugging",
        "confidence": 0.86,
        "error_category": "logic",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-debug-colon",
        "prompt": "Fix the syntax error in: for item in items print(item)",
        "answer": "for item in items:\n    print(item)",
        "task_type": "code_debugging",
        "confidence": 0.97,
        "error_category": "syntax",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-explain-comprehension",
        "prompt": "Explain this Python expression in one concise paragraph: [x * 2 for x in values if x > 0]",
        "answer": "It builds a new list containing twice each positive value from values, while skipping zero and negative values.",
        "task_type": "code_explanation",
        "confidence": 0.88,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-binary-search",
        "prompt": "Describe the invariant that makes binary search correct on a sorted list.",
        "answer": "At every step, target can only remain inside the current inclusive search interval; comparing with the midpoint removes a half that cannot contain target.",
        "task_type": "algorithm_reasoning",
        "confidence": 0.79,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-safe-file",
        "prompt": "Give a safe rule for opening a user-provided file path in a coding assistant example.",
        "answer": "Validate the path against an allowed directory, reject traversal outside it, and avoid executing file contents as code.",
        "task_type": "metacognitive_review",
        "confidence": 0.73,
        "error_category": "unsafe",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-uncertain-api",
        "prompt": "Review an answer that names an unfamiliar library API without a version or test. What should the assistant say?",
        "answer": "State that the API is unverified, check the installed version or official documentation, and provide a small test before presenting it as working.",
        "task_type": "metacognitive_review",
        "confidence": 0.42,
        "error_category": "hallucination",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-code-chunk-text",
        "prompt": "Write a Python function that splits a list into chunks of size size and raises ValueError for non-positive size.",
        "answer": "def chunk(items, size):\n    if size <= 0:\n        raise ValueError('size must be positive')\n    return [items[start:start + size] for start in range(0, len(items), size)]",
        "task_type": "code_generation",
        "confidence": 0.84,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-code-dedupe-order",
        "prompt": "Write a Python function that removes duplicate items while preserving first-seen order.",
        "answer": "def dedupe(items):\n    seen = set()\n    result = []\n    for item in items:\n        if item not in seen:\n            seen.add(item)\n            result.append(item)\n    return result",
        "task_type": "code_generation",
        "confidence": 0.86,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-code-count-vowels",
        "prompt": "Write a Python function that counts vowels in text without distinguishing uppercase from lowercase.",
        "answer": "def count_vowels(text):\n    return sum(char.lower() in 'aeiou' for char in text)",
        "task_type": "code_generation",
        "confidence": 0.9,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-code-safe-division",
        "prompt": "Write a Python function that returns None instead of raising when denominator is zero.",
        "answer": "def safe_divide(numerator, denominator):\n    if denominator == 0:\n        return None\n    return numerator / denominator",
        "task_type": "code_generation",
        "confidence": 0.81,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-debug-mutable-default",
        "prompt": "Fix this function so each call starts with a fresh list: def append_item(item, items=[]): items.append(item); return items",
        "answer": "def append_item(item, items=None):\n    if items is None:\n        items = []\n    items.append(item)\n    return items",
        "task_type": "code_debugging",
        "confidence": 0.91,
        "error_category": "logic",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-debug-missing-return",
        "prompt": "Fix this function so it returns the square: def square(n): n * n",
        "answer": "def square(n):\n    return n * n",
        "task_type": "code_debugging",
        "confidence": 0.98,
        "error_category": "logic",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-debug-membership",
        "prompt": "Fix this function so it returns True when target occurs in values: def contains(values, target): return target not in values",
        "answer": "def contains(values, target):\n    return target in values",
        "task_type": "code_debugging",
        "confidence": 0.96,
        "error_category": "logic",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-debug-except-colon",
        "prompt": "Fix the syntax error in: try: value = int(text) except ValueError print('bad')",
        "answer": "try:\n    value = int(text)\nexcept ValueError:\n    print('bad')",
        "task_type": "code_debugging",
        "confidence": 0.94,
        "error_category": "syntax",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-debug-none-guard",
        "prompt": "Fix this function so it returns an empty string when user is None: def username(user): return user.name",
        "answer": "def username(user):\n    if user is None:\n        return ''\n    return user.name",
        "task_type": "code_debugging",
        "confidence": 0.88,
        "error_category": "logic",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-explain-set-membership",
        "prompt": "Explain why membership checks are usually faster in a set than in a list.",
        "answer": "A set uses hashing to find a candidate bucket, so membership is usually constant time; a list may scan items one by one.",
        "task_type": "code_explanation",
        "confidence": 0.82,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-explain-try-except",
        "prompt": "Explain what a narrow except ValueError block does in Python.",
        "answer": "It catches conversion or validation failures represented by ValueError while allowing unrelated exceptions to propagate.",
        "task_type": "code_explanation",
        "confidence": 0.83,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-explain-generator",
        "prompt": "Explain when (x * x for x in values) computes its values.",
        "answer": "It creates a lazy generator that computes each square as iteration requests it instead of building the full result immediately.",
        "task_type": "code_explanation",
        "confidence": 0.8,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-explain-dict-get",
        "prompt": "Explain what settings.get('timeout', 30) returns when timeout is absent.",
        "answer": "It returns the default value 30 without raising a KeyError.",
        "task_type": "code_explanation",
        "confidence": 0.93,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-two-pointers",
        "prompt": "State the invariant for a two-pointer search for a pair with a target sum in a sorted list.",
        "answer": "The target pair, if it exists, remains inside the interval between the two pointers; a sum below target moves the left pointer right and a sum above target moves the right pointer left.",
        "task_type": "algorithm_reasoning",
        "confidence": 0.78,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-parentheses-stack",
        "prompt": "Describe the data-structure idea for checking balanced parentheses.",
        "answer": "Push opening symbols onto a stack and require each closing symbol to match the most recent unmatched opening symbol; the stack must be empty at the end.",
        "task_type": "algorithm_reasoning",
        "confidence": 0.9,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-bfs-distance",
        "prompt": "Why does breadth-first search find shortest edge-count paths in an unweighted graph?",
        "answer": "A queue visits vertices layer by layer, so the first time a vertex is reached its path uses the fewest edges from the start.",
        "task_type": "algorithm_reasoning",
        "confidence": 0.87,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-stable-sort",
        "prompt": "What property must a sorting algorithm preserve to be called stable?",
        "answer": "Items with equal sort keys must remain in their original relative order.",
        "task_type": "algorithm_reasoning",
        "confidence": 0.92,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-test-small-fix",
        "prompt": "A coding assistant proposes a small fix but has not run it. What should the review label say?",
        "answer": "Mark the fix as unverified, state the expected behavior, and add a focused test before claiming the change works.",
        "task_type": "metacognitive_review",
        "confidence": 0.38,
        "error_category": "incomplete",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-ambiguous-spec",
        "prompt": "What should an assistant do when a coding request does not define behavior for empty input?",
        "answer": "Call out the ambiguity, choose an explicit assumption only if safe, and ask for or add a test that defines the empty-input behavior.",
        "task_type": "metacognitive_review",
        "confidence": 0.46,
        "error_category": "incomplete",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-api-version",
        "prompt": "How should an assistant handle a library API claim when the installed version is unknown?",
        "answer": "Treat the claim as unverified, inspect the installed version or official documentation, and run a minimal compatibility check.",
        "task_type": "metacognitive_review",
        "confidence": 0.44,
        "error_category": "hallucination",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-security-shell",
        "prompt": "Review a coding answer that builds a shell command by concatenating user input. What is the main concern?",
        "answer": "Treat the command as unsafe, avoid shell string concatenation, and pass validated arguments through a restricted execution interface or do not execute them.",
        "task_type": "metacognitive_review",
        "confidence": 0.9,
        "error_category": "unsafe",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-secret-output",
        "prompt": "What should a coding assistant do if a debug log would print an API token?",
        "answer": "Remove the secret from output, redact any diagnostic value, rotate an exposed token, and keep credentials outside prompts and logs.",
        "task_type": "metacognitive_review",
        "confidence": 0.95,
        "error_category": "unsafe",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-counterexample",
        "prompt": "How should an assistant test a claim that a function works for every integer?",
        "answer": "Check ordinary cases, boundaries, negative values, and a targeted counterexample search instead of trusting the claim from one example.",
        "task_type": "metacognitive_review",
        "confidence": 0.7,
        "error_category": "hallucination",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-code-reverse-words",
        "prompt": "Write a Python function that reverses the order of words and collapses extra whitespace.",
        "answer": "def reverse_words(text):\n    return ' '.join(text.split()[::-1])",
        "task_type": "code_generation",
        "confidence": 0.88,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-code-merge-sorted",
        "prompt": "Write a Python function that merges two sorted lists into one sorted list.",
        "answer": "def merge_sorted(left, right):\n    result = []\n    while left and right:\n        result.append((left if left[0] <= right[0] else right).pop(0))\n    return result + left + right",
        "task_type": "code_generation",
        "confidence": 0.68,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-code-is-sorted",
        "prompt": "Write a Python function that returns True when a list is in nondecreasing order.",
        "answer": "def is_sorted(values):\n    return all(a <= b for a, b in zip(values, values[1:]))",
        "task_type": "code_generation",
        "confidence": 0.9,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-code-safe-get",
        "prompt": "Write a Python function that returns mapping[key] or a default when key is absent.",
        "answer": "def safe_get(mapping, key, default=None):\n    return mapping.get(key, default)",
        "task_type": "code_generation",
        "confidence": 0.94,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-code-flatten-once",
        "prompt": "Write a Python function that flattens one level of nested lists.",
        "answer": "def flatten_once(groups):\n    return [item for group in groups for item in group]",
        "task_type": "code_generation",
        "confidence": 0.89,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-debug-average-empty",
        "prompt": "Fix this function so an empty list returns None instead of dividing by zero: def average(values): return sum(values) / len(values)",
        "answer": "def average(values):\n    if not values:\n        return None\n    return sum(values) / len(values)",
        "task_type": "code_debugging",
        "confidence": 0.9,
        "error_category": "logic",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-debug-sort-return",
        "prompt": "Fix this function so it returns sorted values: def ordered(values): result = values.sort(); return result",
        "answer": "def ordered(values):\n    return sorted(values)",
        "task_type": "code_debugging",
        "confidence": 0.91,
        "error_category": "logic",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-debug-equality",
        "prompt": "Fix this condition so it tests value equality: if value is 1: print('one')",
        "answer": "if value == 1:\n    print('one')",
        "task_type": "code_debugging",
        "confidence": 0.86,
        "error_category": "logic",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-explain-enumerate",
        "prompt": "Explain what for index, value in enumerate(values) provides.",
        "answer": "It yields each zero-based position together with the value at that position.",
        "task_type": "code_explanation",
        "confidence": 0.94,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-explain-any",
        "prompt": "Explain what any(flag for flag in flags) returns.",
        "answer": "It returns True when at least one flag is truthy and False when every flag is false or the iterable is empty.",
        "task_type": "code_explanation",
        "confidence": 0.9,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-explain-log-linear",
        "prompt": "Explain why halving a search interval repeatedly gives logarithmic time.",
        "answer": "Each step divides the remaining candidates by two, so only about log2 of the original size steps are needed to reach one candidate.",
        "task_type": "algorithm_reasoning",
        "confidence": 0.84,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-dp-subproblem",
        "prompt": "What makes a problem suitable for dynamic programming?",
        "answer": "It has overlapping subproblems and optimal substructure, so solved smaller states can be stored and reused.",
        "task_type": "algorithm_reasoning",
        "confidence": 0.86,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-review-license",
        "prompt": "What should an assistant check before adding scraped code to training data?",
        "answer": "Verify permission and license, preserve source metadata, remove secrets, and keep an isolated evaluation split.",
        "task_type": "metacognitive_review",
        "confidence": 0.93,
        "error_category": "unsafe",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-review-boundary-test",
        "prompt": "What test cases should review a function that accepts a possibly empty collection?",
        "answer": "Test empty, singleton, ordinary, duplicate, and boundary-sized inputs, then state the expected behavior for each.",
        "task_type": "metacognitive_review",
        "confidence": 0.9,
        "error_category": "incomplete",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-language-welcome",
        "prompt": "Write a warm two-sentence welcome for a community workshop about learning in public.",
        "answer": "Welcome to our workshop. Bring your questions, share your experiments, and learn alongside the group.",
        "task_type": "language_generation",
        "confidence": 0.9,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-language-summary",
        "prompt": "Summarize this in one sentence: Small experiments make failure cheap, reveal useful evidence, and guide the next change.",
        "answer": "Small experiments turn failure into evidence that guides the next change.",
        "task_type": "language_generation",
        "confidence": 0.88,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-language-translate-es",
        "prompt": "Translate to English: La curiosidad convierte una pregunta pequeña en un experimento útil.",
        "answer": "Curiosity turns a small question into a useful experiment.",
        "task_type": "language_generation",
        "confidence": 0.86,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-language-translate-fr",
        "prompt": "Translate to French: Small models can teach us how systems learn.",
        "answer": "Les petits modèles peuvent nous apprendre comment les systèmes apprennent.",
        "task_type": "language_generation",
        "confidence": 0.84,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-language-rewrite",
        "prompt": "Rewrite for clarity: The report maybe needs another check because the result was not really explained.",
        "answer": "The report needs another review because it does not clearly explain the result.",
        "task_type": "language_generation",
        "confidence": 0.87,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-language-explain",
        "prompt": "Explain photosynthesis for a child in two short sentences.",
        "answer": "Plants use sunlight, water, and air to make their own food. This process also releases oxygen for us to breathe.",
        "task_type": "language_generation",
        "confidence": 0.91,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-language-email",
        "prompt": "Write a concise email asking a teammate to review a draft by Friday.",
        "answer": "Subject: Draft review\n\nHi Sam,\nCould you review the draft by Friday and share any edits?\nThanks,\nAlex",
        "task_type": "language_generation",
        "confidence": 0.89,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "train-language-tone",
        "prompt": "Make this sentence friendlier: Send the file by Friday.",
        "answer": "Could you send the file by Friday? Thanks so much.",
        "task_type": "language_generation",
        "confidence": 0.93,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
]

EVAL_ROWS = [
    {
        "id": "eval-factorial-recursion",
        "prompt": "Write a Python function that returns factorial recursively for n >= 0.",
        "answer": "def factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n - 1)",
        "task_type": "code_generation",
        "confidence": 0.78,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "eval-debug-index",
        "prompt": "Fix this function so it returns the first item: def first(items): return items[1]",
        "answer": "def first(items):\n    return items[0]",
        "task_type": "code_debugging",
        "confidence": 0.88,
        "error_category": "logic",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "eval-explain-map",
        "prompt": "Explain what list(map(str, numbers)) returns.",
        "answer": "It returns a list containing the string form of each item in numbers.",
        "task_type": "code_explanation",
        "confidence": 0.82,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "eval-review-uncertainty",
        "prompt": "What should a coding assistant do when its proposed fix has not been run against a test?",
        "answer": "Label the fix as unverified, state the expected behavior, and run or provide a focused test before claiming it works.",
        "task_type": "metacognitive_review",
        "confidence": 0.5,
        "error_category": "incomplete",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "eval-code-clamp",
        "prompt": "Write a Python function that clamps value to the inclusive range from low to high.",
        "answer": "def clamp(value, low, high):\n    return max(low, min(value, high))",
        "task_type": "code_generation",
        "confidence": 0.83,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "eval-debug-default",
        "prompt": "Fix this function so calls do not share state: def add_tag(tag, tags=[]): tags.append(tag); return tags",
        "answer": "def add_tag(tag, tags=None):\n    if tags is None:\n        tags = []\n    tags.append(tag)\n    return tags",
        "task_type": "code_debugging",
        "confidence": 0.9,
        "error_category": "logic",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "eval-bfs-queue",
        "prompt": "What invariant supports a breadth-first search distance map in an unweighted graph?",
        "answer": "When a vertex is first assigned a distance, the queue has reached it by a shortest path, and later visits cannot improve that distance.",
        "task_type": "algorithm_reasoning",
        "confidence": 0.74,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "eval-review-shell",
        "prompt": "What should a coding assistant say about executing a shell command assembled from user input?",
        "answer": "Warn that it is unsafe, avoid shell interpolation, validate arguments, and use a restricted execution boundary only when execution is necessary.",
        "task_type": "metacognitive_review",
        "confidence": 0.88,
        "error_category": "unsafe",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "eval-code-unique-sorted",
        "prompt": "Write a Python function that returns sorted unique values from a list of integers.",
        "answer": "def unique_sorted(values):\n    return sorted(set(values))",
        "task_type": "code_generation",
        "confidence": 0.9,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "eval-code-count-words",
        "prompt": "Write a Python function that counts case-insensitive words in a string.",
        "answer": "def count_words(text):\n    return len(text.lower().split())",
        "task_type": "code_generation",
        "confidence": 0.83,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "eval-debug-last",
        "prompt": "Fix this function so it returns the last item: def last(items): return items[0]",
        "answer": "def last(items):\n    return items[-1]",
        "task_type": "code_debugging",
        "confidence": 0.91,
        "error_category": "logic",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "eval-debug-int-error",
        "prompt": "Fix this function so invalid text returns None: def parse_int(text): return int(text)",
        "answer": "def parse_int(text):\n    try:\n        return int(text)\n    except ValueError:\n        return None",
        "task_type": "code_debugging",
        "confidence": 0.8,
        "error_category": "logic",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "eval-explain-zip",
        "prompt": "Explain what list(zip(names, scores)) produces.",
        "answer": "It creates pairs by taking one item from names and one item from scores at each position.",
        "task_type": "code_explanation",
        "confidence": 0.86,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "eval-topological-order",
        "prompt": "What condition lets a directed graph have a topological ordering?",
        "answer": "It must be acyclic; a directed cycle would require each vertex to appear before another and make a full ordering impossible.",
        "task_type": "algorithm_reasoning",
        "confidence": 0.82,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "eval-review-assumption",
        "prompt": "How should an assistant respond when a coding request leaves empty-input behavior unspecified?",
        "answer": "State the ambiguity, choose a safe assumption or ask for clarification, and add a test that fixes the contract.",
        "task_type": "metacognitive_review",
        "confidence": 0.47,
        "error_category": "incomplete",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "eval-review-path",
        "prompt": "What is the safe review response to a file path built from unchecked user input?",
        "answer": "Validate it against an allowed root, reject traversal, and avoid using the path for execution or privileged access.",
        "task_type": "metacognitive_review",
        "confidence": 0.92,
        "error_category": "unsafe",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "eval-language-summary",
        "prompt": "Summarize this in one sentence: A clear interface gives people room to test an idea without hiding its limits.",
        "answer": "A clear interface supports experimentation while making limitations visible.",
        "task_type": "language_generation",
        "confidence": 0.88,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "eval-language-translate-de",
        "prompt": "Translate to English: Kleine Modelle machen Experimente leichter.",
        "answer": "Small models make experiments easier.",
        "task_type": "language_generation",
        "confidence": 0.85,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "eval-language-rewrite",
        "prompt": "Rewrite for clarity: We changed the setting and then the output was different in a way we did not expect.",
        "answer": "After we changed the setting, the output changed unexpectedly.",
        "task_type": "language_generation",
        "confidence": 0.9,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
    {
        "id": "eval-language-question",
        "prompt": "Answer in two sentences: Why does documenting an experiment help a team?",
        "answer": "Documentation preserves what the team tried and observed. It lets others reproduce the result and choose the next test.",
        "task_type": "language_generation",
        "confidence": 0.9,
        "error_category": "none",
        "source": "project-synthetic",
        "license": "CC0-1.0",
    },
]


def write_jsonl(rows: list[dict], path: str | Path) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False) + "\n")
