"""Verify cached inference, then continue the custom checkpoint on Kaggle."""

from __future__ import annotations

import gc
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import time

PARENT_SHA256 = "395d1b275791eb36f15b2672b94ad8da7d0a9df40b162ff621ace5f41df3edf1"
DATA_HASHES = {
    "broad_train": "b9bd4d4bdac5624df44d8dbc94d4a7eccd6db85e7b564d0b1bad492f4a180203",
    "broad_eval": "6a28b6379f543ee8e52bb26af4d5cdcf3d1ccb1694448a9c6d23ffafdd61b5bb",
    "qa_dev": "11c9eb1675128eb3d76ca735f58e208ee56f528c5f69db7703c4d265bbba3cd8",
    "qa_test": "38f3de1c8a8cc959e7fde4788a96d86b4eff90663dacd8c54d6953ff775c2dc2",
}


def cached_benchmark(torch, checkpoint: Path) -> dict:
    from cognition_slm.generate import load_checkpoint, generate_ids

    model, tokenizer = load_checkpoint(checkpoint, torch.device("cuda"))
    model.eval()
    ids = torch.tensor([tokenizer.encode("Continue this English passage:\n" + "The river flows through the valley. " * 4,
                                        add_eos=False)], device="cuda")
    results = {}
    # Fixed maximum and identical decoding. Report actual generated bytes if EOS occurs.
    for cached in (False, True):
        generate_ids(model, ids, tokenizer, max_new_tokens=2, temperature=0, top_k=0, use_cache=cached)
        torch.cuda.synchronize()
        torch.cuda.reset_peak_memory_stats()
        started = time.perf_counter()
        output = generate_ids(model, ids, tokenizer, max_new_tokens=64, temperature=0, top_k=0, use_cache=cached)
        torch.cuda.synchronize()
        elapsed = time.perf_counter() - started
        count = output.shape[1] - ids.shape[1]
        results["cached" if cached else "uncached"] = {
            "seconds": elapsed, "generated_byte_tokens": count,
            "byte_tokens_per_second": count / elapsed,
            "peak_allocated_bytes": torch.cuda.max_memory_allocated(),
            "ids": output.cpu().tolist(),
        }
    results["identical_greedy_output"] = results["cached"]["ids"] == results["uncached"]["ids"]
    if not results["identical_greedy_output"]:
        raise RuntimeError("500M cached decoding differs from uncached; inspect equivalence before training")
    results["speedup"] = results["uncached"]["seconds"] / results["cached"]["seconds"]
    del model, tokenizer, output
    gc.collect()
    torch.cuda.empty_cache()
    return results


def continuation_command(source: Path, output: Path, *, steps: int, seconds: int) -> list[str]:
    # Resume Adam moments and RNG. A finite step horizon makes cosine decay effective.
    return [sys.executable, "-m", "cognition_slm.train", "--resume", str(source),
            "--data", "artifacts/broad_train.jsonl", "--eval-data", "artifacts/qa_dev.jsonl",
            "--out", str(output), "--steps", str(steps), "--max-seconds", str(seconds),
            "--batch-size", "1", "--gradient-accumulation-steps", "8",
            "--gradient-checkpointing", "--fused-adamw", "--precision", "fp16",
            "--device", "cuda", "--warmup-steps", "200", "--save-every", "250",
            "--eval-every", "500", "--log-every", "50", "--seed", "97"]


def main(*, verify_only: bool = False) -> None:
    if not Path("/kaggle/working").is_dir():
        raise RuntimeError("Run this script on Kaggle; local model execution is prohibited")
    root = Path(__file__).resolve().parents[1]
    os.chdir(root)
    sys.path[:0] = [str(root), str(root / "src"), str(root / "scripts")]
    os.environ.update(PYTHONPATH=str(root / "src"), OMP_NUM_THREADS="2", PYTHONUNBUFFERED="1")
    import torch
    from cognition_slm.data import load_jsonl
    from cognition_slm.checkpoint import load_checkpoint_payload
    from kaggle_english_run import digest, write_json
    from kaggle_500m_quality_run import _final_training_report
    from kaggle_qa_run import evaluate
    from kaggle_long_run import english_samples

    if not torch.cuda.is_available() or (torch.ones(1, device="cuda") + 1).item() != 2:
        raise RuntimeError("A compatible CUDA GPU is required")
    if shutil.disk_usage(root).free < 17 * 1024**3:
        raise RuntimeError("Checkpoint saves require at least 17 GiB of free working disk")
    torch.set_num_threads(2)
    manifest = json.loads((root / "source-manifest.json").read_text())
    for name, expected in manifest.items():
        if digest(root / name) != expected:
            raise RuntimeError(f"Source hash mismatch: {name}")
    subprocess.run([sys.executable, "-m", "unittest", "discover", "-s", "tests", "-v"], check=True)
    matches = list(Path("/kaggle/input").rglob("slm-500m-long-questions.pt"))
    if len(matches) != 1 or digest(matches[0]) != PARENT_SHA256:
        raise RuntimeError("Attach the completed long-training checkpoint with the recorded SHA256")
    source = matches[0]
    artifacts = root / "artifacts"
    artifacts.mkdir(exist_ok=True)
    for name, expected in DATA_HASHES.items():
        path = source.parent / f"{name}.jsonl"
        if digest(path) != expected:
            raise RuntimeError(f"Attached data hash mismatch: {name}")
        shutil.copyfile(path, artifacts / path.name)
    for split in ("broad_eval", "qa_dev", "qa_test"):
        subprocess.run([sys.executable, "-m", "cognition_slm.audit", "--train",
                        "artifacts/broad_train.jsonl", "--eval", f"artifacts/{split}.jsonl"], check=True)
    report = {"status": "verifying", "source_manifest": manifest, "parent_sha256": PARENT_SHA256,
              "gpu": torch.cuda.get_device_name(0), "data_hashes": DATA_HASHES,
              "benchmark": cached_benchmark(torch, source)}
    write_json(root / "efficient_report.json", report)
    payload, config = load_checkpoint_payload(torch, source, inference_only=True)
    start = payload["metadata"]["step"]
    if start != 3142 or config.block_size != 2048:
        raise RuntimeError("Unexpected resume step/context in parent checkpoint")
    del payload
    gc.collect()
    # Verification exercises real optimizer resume with a short time budget.
    output = artifacts / ("optimizer-smoke.pt" if verify_only else "slm-500m-efficient.pt")
    command = continuation_command(source, output, steps=start + 3600,
                                   seconds=10 if verify_only else 14400)
    dev = [(row.to_dict(), [row.answer]) for row in load_jsonl(artifacts / "qa_dev.jsonl")[:32]]
    if not verify_only:
        report["baseline_dev"] = evaluate(torch, source, root, "efficient_baseline_dev", dev)
        report["baseline_english"] = english_samples(torch, source, root, "efficient_baseline")
    log_path = root / "efficient_training.log"
    report["status"] = "training"
    write_json(root / "efficient_report.json", report)
    with log_path.open("w") as log:
        with subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True) as process:
            for line in process.stdout:
                log.write(line)
                log.flush()
                print(line, end="", flush=True)
            if process.wait() != 0:
                raise RuntimeError("Efficient training failed; inspect efficient_training.log")
    report["training"] = _final_training_report(log_path.read_text())
    if verify_only:
        output.unlink()
        report["status"] = "verification_complete"
    else:
        report["development"] = evaluate(torch, output, root, "efficient_final_dev", dev)
        test = [(row.to_dict(), [row.answer]) for row in load_jsonl(artifacts / "qa_test.jsonl")[:32]]
        report["test"] = evaluate(torch, output, root, "efficient_final_test", test)
        report["english"] = english_samples(torch, output, root, "efficient_final")
        from cognition_slm.generate import load_checkpoint, generate_text
        from kaggle_studio_verify import QUESTION_PROBES
        model, tokenizer = load_checkpoint(output, torch.device("cuda"))
        report["general_questions"] = [
            {"id": name, "prompt": prompt, "expected_rubric": rubric,
             "answer": generate_text(model, tokenizer, prompt, task_type=task,
                                     max_new_tokens=256, temperature=0, top_k=0)}
            for name, prompt, task, rubric in QUESTION_PROBES]
        report.update(status="complete_pending_answer_review", checkpoint=str(output), sha256=digest(output))
    write_json(root / "efficient_report.json", report)
    print(report["status"], flush=True)


if __name__ == "__main__":
    main()
